version: '3'
services:
    dockerapp:
        build: .
        ports:
            - "5000:5000" # host port:container port
        depends_on:
            - redis
    redis:
        image: redis:3.2.0
